In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import integrated_gradients as ig
import tensorflow as tf
print(tf.version.GIT_VERSION, tf.version.VERSION)


def one_hot_encode(df, col='utr', seq_len=50):
    nuc_d = {'a':[1,0,0,0],'c':[0,1,0,0],'g':[0,0,1,0],'t':[0,0,0,1], 'n':[0,0,0,0]}
    vectors=np.empty([len(df),seq_len,4])
    
    for i,seq in enumerate(df[col].str[:seq_len]): 
        seq = seq.lower()
        a = np.array([nuc_d[x] for x in seq])
        vectors[i] = a
    return vectors

unknown 1.15.0


In [2]:
data = pd.read_csv('/Users/frederickkorbel/Documents/projects/paper/data/MRL_pred.csv', index_col = False)
mrl_model = tf.keras.models.load_model('/Users/frederickkorbel/Documents/projects/paper/data/seelig/Supplementary Code/modeling/saved_models/main_MRL_model.hdf5')

seq = one_hot_encode(data, seq_len = 50)
ind = data.index
dummy = seq[1]

#igres = ig.integrated_gradients(mrl_model)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [3]:
seq.shape

(20000, 50, 4)

In [4]:
steps = 50
baseline = np.zeros(seq[-1:].shape)

linear_path = np.zeros(tuple([steps] + [t for t in seq[-1:].shape]))
for i in range(steps):
    linear_path[i] = baseline + (seq[-1:] - baseline) * (i*1.0/steps) # baseline + delta * alpha

print(linear_path)

[[[[0.   0.   0.   0.  ]
   [0.   0.   0.   0.  ]
   [0.   0.   0.   0.  ]
   ...
   [0.   0.   0.   0.  ]
   [0.   0.   0.   0.  ]
   [0.   0.   0.   0.  ]]]


 [[[0.   0.   0.02 0.  ]
   [0.   0.   0.   0.02]
   [0.   0.02 0.   0.  ]
   ...
   [0.   0.   0.   0.02]
   [0.02 0.   0.   0.  ]
   [0.02 0.   0.   0.  ]]]


 [[[0.   0.   0.04 0.  ]
   [0.   0.   0.   0.04]
   [0.   0.04 0.   0.  ]
   ...
   [0.   0.   0.   0.04]
   [0.04 0.   0.   0.  ]
   [0.04 0.   0.   0.  ]]]


 ...


 [[[0.   0.   0.94 0.  ]
   [0.   0.   0.   0.94]
   [0.   0.94 0.   0.  ]
   ...
   [0.   0.   0.   0.94]
   [0.94 0.   0.   0.  ]
   [0.94 0.   0.   0.  ]]]


 [[[0.   0.   0.96 0.  ]
   [0.   0.   0.   0.96]
   [0.   0.96 0.   0.  ]
   ...
   [0.   0.   0.   0.96]
   [0.96 0.   0.   0.  ]
   [0.96 0.   0.   0.  ]]]


 [[[0.   0.   0.98 0.  ]
   [0.   0.   0.   0.98]
   [0.   0.98 0.   0.  ]
   ...
   [0.   0.   0.   0.98]
   [0.98 0.   0.   0.  ]
   [0.98 0.   0.   0.  ]]]]


In [5]:
linear_path.squeeze().shape

(50, 50, 4)

In [6]:
ex = ig.integrated_gradients(mrl_model, seq[-1:])

NotImplementedError: tf.GradientTape.gradients() does not support graph control flow operations like tf.cond or tf.while at this time. Use tf.gradients() instead. If you need this feature, please file a feature request at https://github.com/tensorflow/tensorflow/issues/new

In [ ]:
array = np.array([1,2,3])
tensor = tf.convert_to_tensor(array)
tensor.dtype